force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GameProperty__c/GameProperty__c.object-meta.xml
<CustomObject>
    <label>Game Property</label>
    <nameField>
        <displayFormat>GP-{000000}</displayFormat>
        <label>Game Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Game Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GameProperty__c/fields/BuildingCost__c.field-meta.xml
<CustomField>
    <fullName>BuildingCost__c</fullName>
    <label>Building Cost</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Game Properties</relationshipLabel>
    <relationshipName>GameProperties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Game Properties</relationshipLabel>
    <relationshipName>GameProperties</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <formula>IF(Hotel__c == 1, Property__r.RentHotel__c,
IF(Houses__c == 4, Property__r.RentHouse4__c,
IF(Houses__c == 3, Property__r.RentHouse3__c,
IF(Houses__c == 2, Property__r.RentHouse2__c,
IF(Houses__c == 1, Property__r.RentHouse1__c,
IF(IsMonopoly__c == true, Property__r.Rent__c * 2, Property__r.Rent__c))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/RentHotel__c.field-meta.xml
<CustomField>
    <fullName>RentHotel__c</fullName>
    <label>Rent (Hotel)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/RentHouse1__c.field-meta.xml
<CustomField>
    <fullName>RentHouse1__c</fullName>
    <label>Rent (1 House)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/RentHouse3__c.field-meta.xml
<CustomField>
    <fullName>RentHouse3__c</fullName>
    <label>Rent (3 Houses)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/RentHouse4__c.field-meta.xml
<CustomField>
    <fullName>RentHouse4__c</fullName>
    <label>Rent (4 Houses)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GameProperty__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Property&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chance</fullName>
                <default>true</default>
                <label>Chance</label>
            </value>
            <value>
                <fullName>Community Chest</fullName>
            </value>
            <value>
                <fullName>Free Parking</fullName>
            </value>
            <value>
                <fullName>Go To Jail</fullName>
            </value>
            <value>
                <fullName>Jail</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Railroad</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>Go</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A Property record represents a Property card in a Forceopoly game.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/PropertyCost__c.field-meta.xml
<CustomField>
    <fullName>PropertyCost__c</fullName>
    <label>Property Cost</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>Rent</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/RentHouse2__c.field-meta.xml
<CustomField>
    <fullName>RentHouse2__c</fullName>
    <label>Rent (2 Houses)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/lwcBoard.cls
public with sharing class lwcBoard {
    @AuraEnabled
    public static List<GameProperty__c> loadGameProperties(Id gameId) {
        return [select 
            Id, 
            Property__r.Id,
            Property__r.Name, 
            Property__r.Color__c, 
            Property__r.BuildingCost__c, 
            Property__r.Position__c,
            Property__r.PropertyCost__c,
            Property__r.Rent__c,
            Property__r.RentHotel__c,
            Property__r.RentHouse1__c, 
            Property__r.RentHouse2__c,
            Property__r.RentHouse3__c,
            Property__r.RentHouse4__c,
            Property__r.Type__c,
            Property__r.RecordTypeId,
            Property__r.RecordType.Name
            from GameProperty__c 
            where Game__c = :gameId
            order by Property__r.Position__c asc
        ];
    }
    
}